import { Environment, OrbitControls } from "@react-three/drei";
import { Canvas, useFrame, useThree } from "@react-three/fiber";
import Head from "next/head";
import { useEffect, useRef } from "react";
import * as THREE from "three";
import Model from "../components/Ring004"; // Import the generated JSX file

function Controls() {
  const controls = useRef();
  const { camera, gl, set, size } = useThree();
  //@ts-ignore
  useFrame(() => controls.current?.update());

  useEffect(() => {
    const aspect = size.width / size.height;
    const orthoCamera = new THREE.OrthographicCamera(
      -aspect,
      aspect,
      1,
      -1,
      0.1,
      100,
    );
    orthoCamera.position.z = 10;
    set({ camera: orthoCamera });
  }, [set, size]);

  //@ts-ignore
  return <OrbitControls ref={controls} args={[camera, gl.domElement]} />;
}
export default function Home() {
  let modelScale = 0.5;
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex h-screen min-h-screen w-full flex-col items-center justify-center bg-black">
        <Canvas className="h-full w-full">
          <ambientLight />
          <Model scale={[modelScale, modelScale, modelScale]} />
          <Environment files="./Studio-White-Soft.hdr" background={false} />
          <Controls />
        </Canvas>
      </main>
    </>
  );
}
