/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 ring004.glb --transform 
Files: ring004.glb [4.1MB] > ring004-transformed.glb [658.81KB] (84%)
*/

import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const { nodes, materials } = useGLTF("/ring004-transformed.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Circle001.geometry}
        material={materials["Material.002"]}
      />
    </group>
  );
}

useGLTF.preload("/ring004-transformed.glb");
