/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 TECTA_B004_jpeg.glb --transform 
Files: TECTA_B004_jpeg.glb [2.16MB] > TECTA_B004_jpeg-transformed.glb [334.44KB] (85%)
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/TECTA_B004_jpeg-transformed.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="body_final_jpeg" rotation={[0, 0, Math.PI]} scale={-0.1}>
          <mesh name="BL|4c551378-f830-4488-87a2-f486002ac03f_mesh_extrusion,_002" geometry={nodes['BL|4c551378-f830-4488-87a2-f486002ac03f_mesh_extrusion,_002'].geometry} material={materials['steel.002']} />
          <mesh name="BL|4c551378-f830-4488-87a2-f486002ac03f_mesh_extrusion,_002_1" geometry={nodes['BL|4c551378-f830-4488-87a2-f486002ac03f_mesh_extrusion,_002_1'].geometry} material={materials['leather02.002']} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/TECTA_B004_jpeg-transformed.glb')
